db.createView("tweet_count","tweet",[
    {
        $match:{
            area_name:{
                $exists:true
            }
        }

    },
    {$unwind:"$categories"},
    {
	$group:{
		_id:{
		  year:{$year:"$date"},
		  hour:{$hour:"$date"},
		  day:{$dayOfMonth:"$date"},
		  month:{$month:"$date"},
		  area_name:"$area_name",
		  categories:"$categories"
		},
		count:{
			$sum:1
		}
	}},{
		$project:{
			count:1,
			categories:1,
			date: {$dateFromParts:{
				year:"$_id.year",
				month:"$_id.month",
				day:"$_id.day",
				hour:"$_id.hour",
				minute:59,
				second:59,
				millisecond:999,
			}}
		}
	}])